"""add_ear_number_and_tracking_token

Revision ID: 62cd890f1647
Revises: a1b2c3d4e5f6
Create Date: 2026-09-12 00:16:28.303276

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '62cd890f1647'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ear_number', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('tracking_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_projects_ear_number'), 'projects', ['ear_number'], unique=False)
    op.create_index(op.f('ix_projects_tracking_token'), 'projects', ['tracking_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_tracking_token'), table_name='projects')
    op.drop_index(op.f('ix_projects_ear_number'), table_name='projects')
    op.drop_column('projects', 'tracking_token')
    op.drop_column('projects', 'ear_number')
    # ### end Alembic commands ###
