"""add pricing and budget tables

Revision ID: 3c68dffcb604
Revises: 62cd890f1647
Create Date: 2026-09-14 19:31:26.317916

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c68dffcb604'
down_revision: str | None = '62cd890f1647'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trade', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('base_unit_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_pricing_item_code'), 'master_pricing', ['item_code'], unique=True)
    op.create_table('project_budget_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_at_snapshot', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal_sar', sa.Float(), nullable=False),
    sa.Column('vat_sar', sa.Float(), nullable=False),
    sa.Column('total_sar', sa.Float(), nullable=False),
    sa.Column('total_usd', sa.Float(), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budget_summaries_project_id'), 'project_budget_summaries', ['project_id'], unique=False)
    op.create_table('project_stage_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('budget_sar', sa.Float(), nullable=False),
    sa.Column('estimated_sar', sa.Float(), nullable=False),
    sa.Column('committed_sar', sa.Float(), nullable=False),
    sa.Column('remaining_sar', sa.Float(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stage_budgets_project_id'), 'project_stage_budgets', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_stage_budgets_project_id'), table_name='project_stage_budgets')
    op.drop_table('project_stage_budgets')
    op.drop_index(op.f('ix_project_budget_summaries_project_id'), table_name='project_budget_summaries')
    op.drop_table('project_budget_summaries')
    op.drop_index(op.f('ix_master_pricing_item_code'), table_name='master_pricing')
    op.drop_table('master_pricing')
    # ### end Alembic commands ###
